### PR TITLE
Release tool will not crash when publishing a package for the first time

### LINKED ISSUE #491: The new package has not been pushed to GH during the release
That's the state after runnign the release script:

image

Also: 

image

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Release tool will not crash when publishing a package for the first time. Closes #491.

### CODE REVIEW

File: packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js [hunk 1]
```diff
@@ -256,6 +256,26 @@ module.exports = function releaseSubRepositories( options ) {
...
+				const errorAsArray = err.message.split( '\n' ).slice( 0, 2 );
+
+				if (
+					errorAsArray[ 0 ].endsWith( 'npm ERR! code E404' ) &&
+					errorAsArray[ 1 ] === `npm ERR! 404 '${ packageName }' is not in the npm registry.`
+				) {
+					return null;
+				}
+
+				throw new Error( err );
```
Comment (ma2ciek) [inline packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js]: or `throw err` since the error is already created?

Comment (pomek) [inline packages/ckeditor5-dev-env/lib/release-tools/tasks/releasesubrepositories.js]:
```suggestion
				throw err;
```
