### PR TITLE
T/343: PostCSS does not work on Windows

### LINKED ISSUE #343: PostCSS does not work on Windows
This line:

https://github.com/ckeditor/ckeditor5-dev/blob/95bcfd88e65e89a917b3461622a88dc6445b4fc0/packages/ckeditor5-dev-utils/lib/styles/themeimporter.js#L191

should be modified:

```diff
-       const match = inputFilePath.match( `ckeditor5-[^${ path.sep }]+` );
+       const match = inputFilePath.match( /ckeditor5-[^\\/]+/ );
```

Thanks to that, PostCSS should work on Windows (finally).

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Changed invalid regexp on Windows environments for importing themes (PostCSS). Closes #343.

---

Before merging this, check this out on Windows machine. It works for me but for unknown reasons may it does not work on your machine.

### CODE REVIEW

File: packages/ckeditor5-dev-utils/lib/styles/themeimporter.js [hunk 1]
```diff
@@ -188,7 +188,7 @@ function getThemeFilePath( themePath, inputFilePath ) {
 // @param {String} inputFilePath A path to the file.
 // @returns {String} The name of the package.
 function getPackageName( inputFilePath ) {
-	const match = inputFilePath.match( `ckeditor5-[^${ path.sep }]+` );
+	const match = inputFilePath.match( /ckeditor5-[^\\/]+/ );
```
Comment (ma2ciek) [inline packages/ckeditor5-dev-utils/lib/styles/themeimporter.js]: Did it work earlier at all?

Comment (ma2ciek) [reply packages/ckeditor5-dev-utils/lib/styles/themeimporter.js]: Ok. I'm stupid. nevermind.
